parameters:
#    kh_core_db.example.class: KH\CoreDBBundle\Example

services:
#    kh_core_db.example:
#        class: %kh_core_db.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
